import Http from '@/utils/Http'

/** 获取作业列表 */
export const jobList = (params: any) => {
	return [null, {
		code: 200,
		msg: 'ok',
		total: 1007,
		data: [{
				"id": 1096,
				"jobName": "波士顿大龙虾40箱",
				"jobType": "入库单",
				"taskId": 1053,
				"actionId": 11330,
				"taskMode": 1,
				"lifeCycle": 1,
				"cron": "10箱",
				"modeUnit": "D",
				"jobBu": "1对1",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "清明",
				"ownerUserId": "1071308198",
				"description": "活动商品表",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-17 12:50:45",
				"updateTime": "2021-03-17 12:51:03",
				"targetTable": "",
				"increType": "天全量"
			},
			{
				"id": 1095,
				"jobName": "钟赛高雪糕150箱",
				"jobType": "出库单",
				"taskId": 236,
				"actionId": 11329,
				"taskMode": 1,
				"lifeCycle": 1,
				"cron": "900盒",
				"modeUnit": "D",
				"jobBu": "优课",
				"runStatus": 0,
				"lastSuccessTime": null,
				"owner": "陈奕迅",
				"ownerUserId": "1053314029",
				"description": "报表展示",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-17 12:06:11",
				"updateTime": "2021-03-17 12:06:15",
				"targetTable": "",
				"increType": "-"
			},
			{
				"id": 1094,
				"jobName": "可优比儿童滑板车",
				"jobType": "出库单",
				"taskId": 235,
				"actionId": 11328,
				"taskMode": 1,
				"lifeCycle": 0,
				"cron": "900盒",
				"modeUnit": "D",
				"jobBu": "优课",
				"runStatus": 0,
				"lastSuccessTime": null,
				"owner": "陈奕迅",
				"ownerUserId": "1053314029",
				"description": "报表展示",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-17 12:05:11",
				"updateTime": "2021-03-17 13:18:31",
				"targetTable": "进价略高于往期",
				"increType": "-"
			},
			{
				"id": 1093,
				"jobName": "iMac 27寸电脑",
				"jobType": "出库单",
				"taskId": 234,
				"actionId": 11327,
				"taskMode": 1,
				"lifeCycle": 1,
				"cron": "900盒",
				"modeUnit": "D",
				"jobBu": "优课",
				"runStatus": 0,
				"lastSuccessTime": null,
				"owner": "陈奕迅",
				"ownerUserId": "1053314029",
				"description": "报表展示",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-17 12:04:07",
				"updateTime": "2021-03-17 12:04:21",
				"targetTable": "",
				"increType": "-"
			},
			{
				"id": 1092,
				"jobName": "Macbook Pro 13.3寸",
				"jobType": "出库单",
				"taskId": 233,
				"actionId": 11326,
				"taskMode": 1,
				"lifeCycle": 1,
				"cron": "900盒",
				"modeUnit": "D",
				"jobBu": "优课",
				"runStatus": 0,
				"lastSuccessTime": null,
				"owner": "陈奕迅",
				"ownerUserId": "1053314029",
				"description": "报表展示",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-17 12:02:38",
				"updateTime": "2021-03-17 12:02:42",
				"targetTable": "",
				"increType": "-"
			},
			{
				"id": 1091,
				"jobName": "雀巢咖啡",
				"jobType": "出库单",
				"taskId": 232,
				"actionId": 11325,
				"taskMode": 1,
				"lifeCycle": 1,
				"cron": "900盒",
				"modeUnit": "D",
				"jobBu": "优课",
				"runStatus": 0,
				"lastSuccessTime": null,
				"owner": "陈奕迅",
				"ownerUserId": "1053314029",
				"description": "报表展示",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-17 12:01:22",
				"updateTime": "2021-03-17 12:01:32",
				"targetTable": "还有100盒待出库",
				"increType": "-"
			},
			{
				"id": 1090,
				"jobName": "新西兰进口三文鱼",
				"jobType": "入库单",
				"taskId": 1052,
				"actionId": 11323,
				"taskMode": 1,
				"lifeCycle": 1,
				"cron": "10箱",
				"modeUnit": "D",
				"jobBu": "1对1",
				"runStatus": 0,
				"lastSuccessTime": null,
				"owner": "牧笛",
				"ownerUserId": "1079922413",
				"description": "代理商数据同步",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-17 11:02:48",
				"updateTime": "2021-03-17 11:04:17",
				"targetTable": "",
				"increType": "天全量"
			},
			{
				"id": 1089,
				"jobName": "加州鲈鱼",
				"jobType": "出库单",
				"taskId": 231,
				"actionId": 11321,
				"taskMode": 1,
				"lifeCycle": 2,
				"cron": "5吨",
				"modeUnit": "D",
				"jobBu": "小狸",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "周杰伦",
				"ownerUserId": "1071855272",
				"description": "光子用户打通表推送到MySQL",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-17 10:31:36",
				"updateTime": "2021-03-17 10:32:16",
				"targetTable": "",
				"increType": "-"
			},
			{
				"id": 1088,
				"jobName": "Nike",
				"jobType": "入库单",
				"taskId": 1051,
				"actionId": 11313,
				"taskMode": 1,
				"lifeCycle": 2,
				"cron": "200双",
				"modeUnit": "h",
				"jobBu": "少儿",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "国庆",
				"ownerUserId": "1038905571",
				"description": "小时表",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-16 18:52:27",
				"updateTime": "2021-03-16 18:53:22",
				"targetTable": "2双残次品，预备低价处理",
				"increType": "小时全量"
			},
			{
				"id": 1087,
				"jobName": "晨光黑色中性笔",
				"jobType": "入库单",
				"taskId": 1050,
				"actionId": 11312,
				"taskMode": 1,
				"lifeCycle": 2,
				"cron": "200双",
				"modeUnit": "h",
				"jobBu": "少儿",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "国庆",
				"ownerUserId": "1038905571",
				"description": "小时表",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-16 18:49:52",
				"updateTime": "2021-03-16 18:53:28",
				"targetTable": "",
				"increType": "小时全量"
			},
			{
				"id": 1086,
				"jobName": "联想笔记本电脑",
				"jobType": "入库单",
				"taskId": 1049,
				"actionId": 11307,
				"taskMode": 1,
				"lifeCycle": 2,
				"cron": "0 0 3 * * ?",
				"modeUnit": "D",
				"jobBu": "小狸",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "荷艳",
				"ownerUserId": "1070064353",
				"description": "光子加群数据需求",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-16 15:09:50",
				"updateTime": "2021-03-16 15:52:48",
				"targetTable": "",
				"increType": "天全量"
			},
			{
				"id": 1085,
				"jobName": "小米厨下式水质净化器Pro",
				"jobType": "入库单",
				"taskId": 1048,
				"actionId": 11301,
				"taskMode": 1,
				"lifeCycle": 1,
				"cron": "2000只",
				"modeUnit": "D",
				"jobBu": "1对1",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "佑翰",
				"ownerUserId": "1025801569",
				"description": "学生薄弱科目扩展表",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-16 10:49:37",
				"updateTime": "2021-03-16 10:49:53",
				"targetTable": "",
				"increType": "天全量"
			},
			{
				"id": 1084,
				"jobName": "AKBAR新加坡红茶",
				"jobType": "出库单",
				"taskId": 230,
				"actionId": 11289,
				"taskMode": 1,
				"lifeCycle": 1,
				"cron": "900盒",
				"modeUnit": "D",
				"jobBu": "优课",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "陈奕迅",
				"ownerUserId": "1053314029",
				"description": "同步数据",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-15 16:52:22",
				"updateTime": "2021-03-15 17:39:55",
				"targetTable": "",
				"increType": "-"
			},
			{
				"id": 1083,
				"jobName": "LOOK眼睛",
				"jobType": "出库单",
				"taskId": 229,
				"actionId": 11288,
				"taskMode": 1,
				"lifeCycle": 2,
				"cron": "0 0 3 * * ?",
				"modeUnit": "D",
				"jobBu": "小狸",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "周杰伦",
				"ownerUserId": "1071855272",
				"description": "光子群每日活跃用户发消息数",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-15 16:43:53",
				"updateTime": "2021-03-16 11:02:07",
				"targetTable": "",
				"increType": "-"
			},
			{
				"id": 1082,
				"jobName": "Javascript设计模式",
				"jobType": "入库单",
				"taskId": 1047,
				"actionId": 11273,
				"taskMode": 1,
				"lifeCycle": 2,
				"cron": "10箱",
				"modeUnit": "D",
				"jobBu": "优课",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "国栋",
				"ownerUserId": "1077880257",
				"description": "因为我数据有需求 所以我要迁",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-15 14:20:57",
				"updateTime": "2021-03-15 14:24:20",
				"targetTable": "",
				"increType": "天全量"
			},
			{
				"id": 1081,
				"jobName": "公牛无线插座USB版",
				"jobType": "入库单",
				"taskId": 1046,
				"actionId": 11272,
				"taskMode": 1,
				"lifeCycle": 1,
				"cron": "5吨",
				"modeUnit": "D",
				"jobBu": "1对1",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "雨田",
				"ownerUserId": "1054949372",
				"description": "转介绍学生标签表",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-15 13:57:25",
				"updateTime": "2021-03-15 13:57:33",
				"targetTable": "",
				"increType": "天全量"
			},
			{
				"id": 1080,
				"jobName": "Magic Mouse 2",
				"jobType": "出库单",
				"taskId": 228,
				"actionId": 11258,
				"taskMode": 1,
				"lifeCycle": 2,
				"cron": "5吨",
				"modeUnit": "D",
				"jobBu": "小狸",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "周杰伦",
				"ownerUserId": "1071855272",
				"description": "光子群用户每日进群退群统计表推数",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-12 21:09:52",
				"updateTime": "2021-03-16 10:57:31",
				"targetTable": "",
				"increType": "-"
			},
			{
				"id": 1079,
				"jobName": "Air Pods Pro",
				"jobType": "入库单",
				"taskId": 1044,
				"actionId": 11246,
				"taskMode": 1,
				"lifeCycle": 1,
				"cron": "2000只",
				"modeUnit": "D",
				"jobBu": "优课",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "梦媛",
				"ownerUserId": "1074140064",
				"description": "班级-微信群关联表",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-12 15:21:09",
				"updateTime": "2021-03-12 15:59:39",
				"targetTable": "",
				"increType": "天全量"
			},
			{
				"id": 1078,
				"jobName": "绿联手机支架",
				"jobType": "入库单",
				"taskId": 1043,
				"actionId": 11225,
				"taskMode": 1,
				"lifeCycle": 2,
				"cron": "200双",
				"modeUnit": "h",
				"jobBu": "优课",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "婷婷",
				"ownerUserId": "1072805316",
				"description": "优课员工表",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-11 16:57:52",
				"updateTime": "2021-03-11 16:58:17",
				"targetTable": "",
				"increType": "小时全量"
			},
			{
				"id": 1077,
				"jobName": "B&O无线耳机",
				"jobType": "入库单",
				"taskId": 1042,
				"actionId": 11224,
				"taskMode": 1,
				"lifeCycle": 2,
				"cron": "10箱",
				"modeUnit": "D",
				"jobBu": "优课",
				"runStatus": 1,
				"lastSuccessTime": null,
				"owner": "婷婷",
				"ownerUserId": "1072805316",
				"description": "优课员工表",
				"speedChannel": 1,
				"errorRecord": 0,
				"fetchSize": null,
				"jobJson": null,
				"isDisable": 0,
				"createTime": "2021-03-11 16:55:25",
				"updateTime": "2021-03-15 10:57:46",
				"targetTable": "",
				"increType": "天全量"
			}
		]
	}]
	Http.ask(`POST`, `/jobList`, params)
}